### ISSUE TITLE
ISMEAR=0  work?

### ISSUE THREAD

**Issue by quantumable** [TRIQS/dft_tools#174] opened 2021-08-13 00:01 UTC
Dear Triqs devs,

I have successfully followed the tutorial you proposed for the DFT+DMFT calculation for the case of SrVO3.
I have a problem with my system which is a molecule that I do not use the tetrahedron method. I use ISMEAR=0. But the system trash when "plovasp plo.cfg". Can you tell me if the code works with ISMEAR=0 or if you have a suggestion when I use ISMEAR=0?

**Comment by the-hampel** [comment] 2021-08-13 13:21
Hi Olivier,

Can you tell me a bit more about the error you observe? That is not really helping me to identify the problem. I can say, that the Vasp converter (are you talking about the Vasp converter? Please make that clear!) works for all `ISMEAR` values. The only thing that only works for `ISMEAR=-5` is the calculation of the DOS in `plovasp` . So probably you have the tag `DOSMESH` in your `plo.cfg`? Otherwise there should be no problems.

- Alex

**Comment by quantumable** [comment] 2021-08-13 18:57
thank you for your reply. 
indeed by removing the DOSMESH parameter it works. just to be sure to have understood the different parameters corresponding to the energy windows.  Emin and Emax represent here the energy window where we have an important weight of the target orbitals. and the EWINDOW parameter represents (Emin-Ef; Emax-Ef) ?

Olivier

**Comment by quantumable** [comment] 2021-08-13 18:58
thank you for your reply.
indeed by removing the DOSMESH parameter it works. just to be sure to have
understood the different parameters corresponding to the energy windows.
Emin and Emax represent here the energy window where we have an important
weight of the target orbitals. and the EWINDOW parameter represents
(Emin-Ef; Emax-Ef) ?

Olivier

**Comment by the-hampel** [comment] 2021-08-13 20:32
Very good. Yes indeed. The energy window is given relative to the Fermi Level as you write. Importantly the window also determines in which window the projectors are orthonormalized. A smaller window will produce more extended projector functions, but occupations closer to band fillings (it will spread some of the electrons on tails to other orbitals), wheres a larger window will produce more localized projectors, because weight can live on other bands. This is pretty much up to you to decide. Depending on the problem and the physics you want to capture. 

Here is an example for SrMoO3 for different choices of windows: 
![image](https://user-images.githubusercontent.com/21337117/129415072-665f2a0f-d6cc-4f9e-b00a-82e1870e19f3.png)
* gray: VASP total DOS (no good kpoint convergence, just for illustration)
* purple: 3 projectors for the 3 t2g orbitals at the Fermi level with window -2.5 to 2 eV
* orange: same projectors but for window -9 to 9 eV. You can see less DOS around E_f, but some weight at lower energies where the oxygens are
* blue 5 projectors for all 5 d orbitals in the larger window

**Comment by quantumable** [comment] 2021-08-13 22:28
I work on the Kondo effect. I chose EMIN=-18eV EMAX=5.  
I have some questions:

Since I have a magnetic system as in the example, why is the non-magnetic calculation done during the vasp calculation?
in the INCAR file I have this for example LORBIT=14
LOCPROJ = 1 : d : Pr 2
LOCPROJ = 2 4 6 9 : p : Pr 2

the parameter "IONS"(plo.cfg) is not clear for me. how to define the shell for the 4 atoms of N interacting with the atoms subject of the correlation in the file? like here? or it is necessary to define for each atom a shell

BASENAME = Mn
[Group 1]
SHELLS = 1 2
EWINDOW = -5 4
NORMION = False
NORMALIZE = True
[Shell 1] # Mn d shell
LSHELL = 2
IONS = 1
CORR = True
TRANSFORM = 1.0  0.0  0.0  0.0  0.0
                           0.0  1.0  0.0  0.0  0.0
                           0.0  0.0  1.0  0.0  0.0
                           0.0  0.0  0.0  1.0  0.0
                           0.0  0.0  0.0  0.0  1.0
[Shell 2] # N p shell
LSHELL = 1
IONS = 2  4  6 9
CORR = False
TRANSFORM = 1.0  0.0  0.0
                           0.0  1.0  0.0
                           0.0  0.0  1.0

**Comment by quantumable** [comment] 2021-08-13 23:12
I also have a problem with the cript for the calculation of the local lattice green's function [Nio_local_lattice_GF.py](https://triqs.github.io/dft_tools/latest/tutorials/nio_csc.html) from the tutorial when I run it I have this error 

Starting run with 112 MPI rank(s) at : 2021-08-14 00:59:42.279120
Traceback (most recent call last):
  File "/home/olivier/WORK_tuto_Ni/ NiO_local_lattice_GF.py", line 59, in <module>
    n_orbs = SK.proj_mat_csc.shape[2]
AttributeError: 'NoneType' object has no attribute 'shape'
Traceback (most recent call last):
  File "/home/olivier/WORK_tuto_Ni/NiO_local_lattice_GF.py", line 59, in <module>
    n_orbs = SK.proj_mat_csc.shape[2]
AttributeError: 'NoneType' object has no attribute 'shape'
Traceback (most recent call last):

how to solve this?

**Comment by quantumable** [comment] 2021-08-15 20:50
Since you have not answered yet, I take the opportunity to ask this additional problem concerning my system (which is a molecule). After having followed the steps (1-calculating dft with the projection LOCPROJ = 1 : d : Pr ; LOCPROJ = 2 4 6 9 : p : Pr and adding of course the fermi energy in the LOCPROJ file and after having done 2-) plovasp plo. cfg and 3-) python convert.py 4-) when executing the script dmft_ctqmc.py I have this error which does not appear when I use the same script for the example of the Nio tutorial.
error: 

 File "/home2020/home/MnPc_DMFT/f.py", line 139, in <module>
    S.solve(h_int = H, **p)
  File "/home2020/home/triqs/install/lib/python3.8/site-packages/triqs_cthyb/solver.py", line 140, in solve
    solve_status = SolverCore.solve(self, **params_kw)
RuntimeError: .. Error occurred at Sun Aug 15 10:21:17 2021

.. Error .. calling C++ overload
.. solve() -> void
.. in implementation of method SolverCore.solve
.. C++ error was :
.. Triqs runtime error at /home2020/home/triqs/cthyb.src/c++/triqs_cthyb/solver_core.cpp : 141

Largest imaginary element of delta(infty) e.g. of the local part of G0: 0.000124901, is larger than the set parameter imag_threshold 1e-13
.. Error occurred on node 22

Traceback (most recent call last):
  File "/home2020/home/MnPc_DMFT/f.py", line 139, in <module>
    S.solve(h_int = H, **p)
  File "/home2020/home/triqs/install/lib/python3.8/site-packages/triqs_cthyb/solver.py", line 140, in solve
    solve_status = SolverCore.solve(self, **params_kw)
RuntimeError: .. Error occurred at Sun Aug 15 10:21:17 2021

.. Error .. calling C++ overload
.. solve() -> void
.. in implementation of method SolverCore.solve
.. C++ error was :
.. Triqs runtime error at /home2020/home/triqs/cthyb.src/c++/triqs_cthyb/solver_core.cpp : 141

Largest imaginary element of delta(infty) e.g. of the local part of G0: 0.000124901, is larger than the set parameter imag_threshold 1e-13
.. Error occurred on node 26






script................................................................





from itertools import *
import numpy as np
import triqs.utility.mpi as mpi
from h5 import *
# from triqs.archive import *
from triqs.gf import *
import sys, triqs.version as triqs_version
from triqs_dft_tools.sumk_dft import *
from triqs_dft_tools.sumk_dft_tools import *
from triqs.operators.util.hamiltonians import *
from triqs.operators.util.U_matrix import *
from triqs_cthyb import *
import triqs_cthyb.version as cthyb_version
import triqs_dft_tools.version as dft_tools_version

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

filename = 'nio'

SK = SumkDFT(hdf_file = filename+'.h5', use_dft_blocks = False)

beta = 5.0 
 
Sigma = SK.block_structure.create_gf(beta=beta)
SK.put_Sigma([Sigma])
G = SK.extract_G_loc()
SK.analyse_block_structure_from_gf(G, threshold = 1e-3)
for i_sh in range(len(SK.deg_shells)):
    num_block_deg_orbs = len(SK.deg_shells[i_sh])
    mpi.report('found {0:d} blocks of degenerate orbitals in shell {1:d}'.format(num_block_deg_orbs, i_sh))
    for iblock in range(num_block_deg_orbs):
        mpi.report('block {0:d} consists of orbitals:'.format(iblock))
        for keys in SK.deg_shells[i_sh][iblock].keys():
            mpi.report('  '+keys)

# Setup CTQMC Solver

n_orb = SK.corr_shells[0]['dim']
spin_names = ['up','down']
orb_names = [i for i in range(0,n_orb)]

#gf_struct = set_operator_structure(spin_names, orb_names, orb_hyb)
gf_struct = SK.gf_struct_solver[0]
mpi.report('Sumk to Solver: %s'%SK.sumk_to_solver)
mpi.report('GF struct sumk: %s'%SK.gf_struct_sumk)
mpi.report('GF struct solver: %s'%SK.gf_struct_solver)

S = Solver(beta=beta, gf_struct=gf_struct)

# Construct the Hamiltonian and save it in Hamiltonian_store.txt
H = Operator() 
U = 8.0
J = 1.0


U_sph = U_matrix(l=2, U_int=U, J_hund=J)
U_cubic = transform_U_matrix(U_sph, spherical_to_cubic(l=2, convention=''))
Umat, Upmat = reduce_4index_to_2index(U_cubic)

H = h_int_density(spin_names, orb_names, map_operator_structure=SK.sumk_to_solver[0], U=Umat, Uprime=Upmat)

# Print some information on the master node
mpi.report('Greens function structure is: %s '%gf_struct)
mpi.report('U Matrix set to:\n%s'%Umat)
mpi.report('Up Matrix set to:\n%s'%Upmat)

# Parameters for the CTQMC Solver
p = {}
p["max_time"] = -1
p["random_name"] = ""
p["random_seed"] = 123 * mpi.rank + 567
p["length_cycle"] = 100
p["n_warmup_cycles"] = 20000
p["n_cycles"] = 200000
p["fit_max_moment"] = 4
p["fit_min_n"] = 30
p["fit_max_n"] = 50
p["perform_tail_fit"] = True

# Double Counting: 0 FLL, 1 Held, 2 AMF
DC_type = 0
DC_value = 59.0

# Prepare hdf file and and check for previous iterations
n_iterations = 2

iteration_offset = 0
if mpi.is_master_node():
    ar = HDFArchive(filename+'.h5','a')
    if not 'DMFT_results' in ar: ar.create_group('DMFT_results')
    if not 'Iterations' in ar['DMFT_results']: ar['DMFT_results'].create_group('Iterations')
    if not 'DMFT_input' in ar: ar.create_group('DMFT_input')
    if not 'Iterations' in ar['DMFT_input']: ar['DMFT_input'].create_group('Iterations')
    if not 'code_versions' in ar['DMFT_input']: ar['DMFT_input'].create_group('code_versio\
ns')
    ar['DMFT_input']['code_versions']["triqs_version"] = triqs_version.version
    ar['DMFT_input']['code_versions']["triqs_git"] = triqs_version.git_hash
    ar['DMFT_input']['code_versions']["cthyb_version"] = cthyb_version.version
    ar['DMFT_input']['code_versions']["cthyb_git"] = cthyb_version.triqs_cthyb_hash
    ar['DMFT_input']['code_versions']["dft_tools_version"] = dft_tools_version.version
    ar['DMFT_input']['code_versions']["dft_tools_version"] = dft_tools_version.triqs_dft_tools_hash
    if 'iteration_count' in ar['DMFT_results']: 
        iteration_offset = ar['DMFT_results']['iteration_count']+1
        S.Sigma_iw = ar['DMFT_results']['Iterations']['Sigma_it'+str(iteration_offset-1)]
        SK.dc_imp = ar['DMFT_results']['Iterations']['dc_imp'+str(iteration_offset-1)]
        SK.dc_energ = ar['DMFT_results']['Iterations']['dc_energ'+str(iteration_offset-1)]
        SK.chemical_potential = ar['DMFT_results']['Iterations']['chemical_potential'+str(iteration_offset-1)].real
    ar['DMFT_input']["dmft_script_it"+str(iteration_offset)] = open(sys.argv[0]).read()
iteration_offset = mpi.bcast(iteration_offset)
S.Sigma_iw = mpi.bcast(S.Sigma_iw)
SK.dc_imp = mpi.bcast(SK.dc_imp)
SK.dc_energ = mpi.bcast(SK.dc_energ)
SK.chemical_potential = mpi.bcast(SK.chemical_potential)

# Calc the first G0
SK.symm_deg_gf(S.Sigma_iw,ish=0)
SK.put_Sigma(Sigma_imp = [S.Sigma_iw])
SK.calc_mu(precision=0.01)
S.G_iw << SK.extract_G_loc()[0]
SK.symm_deg_gf(S.G_iw, ish=0)

#Init the DC term and the self-energy if no previous iteration was found
if iteration_offset == 0:
    dm = S.G_iw.density()
    SK.calc_dc(dm, U_interact=U, J_hund=J, orb=0, use_dc_formula=DC_type,use_dc_value=DC_value)
    S.Sigma_iw << SK.dc_imp[0]['up'][0,0]

mpi.report('%s DMFT cycles requested. Starting with iteration %s.'%(n_iterations,iteration_offset))

# The infamous DMFT self consistency cycle
for it in range(iteration_offset, iteration_offset + n_iterations):
    
    mpi.report('Doing iteration: %s'%it)
    
    # Get G0
    S.G0_iw << inverse(S.Sigma_iw + inverse(S.G_iw))
    # Solve the impurity problem
    S.solve(h_int = H, **p)
    if mpi.is_master_node(): 
        ar['DMFT_input']['Iterations']['solver_dict_it'+str(it)] = p
        ar['DMFT_results']['Iterations']['Gimp_it'+str(it)] = S.G_iw
        ar['DMFT_results']['Iterations']['Gtau_it'+str(it)] = S.G_tau
        ar['DMFT_results']['Iterations']['Sigma_uns_it'+str(it)] = S.Sigma_iw
    # Calculate double counting
    dm = S.G_iw.density()
    SK.calc_dc(dm, U_interact=U, J_hund=J, orb=0, use_dc_formula=DC_type,use_dc_value=DC_value)
    # Get new G
    SK.symm_deg_gf(S.Sigma_iw,ish=0)
    SK.put_Sigma(Sigma_imp=[S.Sigma_iw])
    SK.calc_mu(precision=0.01)
    S.G_iw << SK.extract_G_loc()[0]
    
    # print densities
    for sig,gf in S.G_iw:
        mpi.report("Orbital %s density: %.6f"%(sig,dm[sig][0,0].real))
    mpi.report('Total charge of Gloc : %.6f'%S.G_iw.total_density().real)

    if mpi.is_master_node(): 
        ar['DMFT_results']['iteration_count'] = it
        ar['DMFT_results']['Iterations']['Sigma_it'+str(it)] = S.Sigma_iw
        ar['DMFT_results']['Iterations']['Gloc_it'+str(it)] = S.G_iw
        ar['DMFT_results']['Iterations']['G0loc_it'+str(it)] = S.G0_iw
        ar['DMFT_results']['Iterations']['dc_imp'+str(it)] = SK.dc_imp
        ar['DMFT_results']['Iterations']['dc_energ'+str(it)] = SK.dc_energ
        ar['DMFT_results']['Iterations']['chemical_potential'+str(it)] = SK.chemical_potential

if mpi.is_master_node(): del ar

**Comment by the-hampel** [comment] 2021-08-16 15:28
These are many questions. I cannot answer all of your system related questions. I can only try to answer some technical questions / issues you asked here. Let's start here:

> I also have a problem with the cript for the calculation of the local lattice green's function [Nio_local_lattice_GF.py](https://triqs.github.io/dft_tools/latest/tutorials/nio_csc.html) from the tutorial when I run it I have this error
> 
> Starting run with 112 MPI rank(s) at : 2021-08-14 00:59:42.279120
> Traceback (most recent call last):
> File "/home/olivier/WORK_tuto_Ni/ NiO_local_lattice_GF.py", line 59, in
> n_orbs = SK.proj_mat_csc.shape[2]
> AttributeError: 'NoneType' object has no attribute 'shape'
> Traceback (most recent call last):
> File "/home/olivier/WORK_tuto_Ni/NiO_local_lattice_GF.py", line 59, in
> n_orbs = SK.proj_mat_csc.shape[2]
> AttributeError: 'NoneType' object has no attribute 'shape'
> Traceback (most recent call last):
> 
> how to solve this?

I think the error message is pretty clear. The object `SK.proj_mat_csc` does not exist. I checked the script. Which is actually the fille `NiO_local_lattice_GF.py` and I think there is a mistake there. I will fix that. You have to change line 59 to 
```
n_orbs = SK.proj_mat.shape[2]
```
. Let me know if that works. I will try as well. Next let's take a look at this error: 

> 
> File "/home2020/home/MnPc_DMFT/f.py", line 139, in
> S.solve(h_int = H, **p)
> File "/home2020/home/triqs/install/lib/python3.8/site-packages/triqs_cthyb/solver.py", line 140, in solve
> solve_status = SolverCore.solve(self, **params_kw)
> RuntimeError: .. Error occurred at Sun Aug 15 10:21:17 2021
> 
> .. Error .. calling C++ overload
> .. solve() -> void
> .. in implementation of method SolverCore.solve
> .. C++ error was :
> .. Triqs runtime error at /home2020/home/triqs/cthyb.src/c++/triqs_cthyb/solver_core.cpp : 141
> 
> Largest imaginary element of delta(infty) e.g. of the local part of G0: 0.000124901, is larger than the set parameter imag_threshold 1e-13
> .. Error occurred on node 22

This error occurs when your projectors are not well converged and produce imaginary overlap between orbitals. Like imaginary hopping amplitudes. The script is doing exactly what it is supposed to do and crashes because the input is not good. In this case the cthyb solver complains to you. Please try to converge your input KS states from VASP better before doing the projection. Make sure that the column `rms` is converged down to 10-8 or lower. See also here for some details: https://flatironinstitute.github.io/solid_dmft/md_notes/vasp_csc.html#convergence-of-projectors-with-vasp . 

If you are actually treating a molecule it might be beneficial to actually use the wannier90 interface instead. Wannier90 MLWF are way more controlled for hyb orbitals than projectors and you can visualize them. Did you look into that?

**Comment by the-hampel** [comment] 2021-08-16 16:54
I fixed now the example with commit https://github.com/TRIQS/dft_tools/commit/a1b5421864a53ce17aea81cdd2ca803db1e269b0 . You do not necessarily update your installation, but indeed the tutorial was wrong. I fixed both the `plo.cfg` and the `converter.py` script. The `NiO_local_lattice_GF.py` was doing the right thing, but the converter was not correctly setup. Let me know if there are still problems with that. I also changed the `INCAR` file a bit for NiO, to have a bitter better accuracy. The changes can also be directly be seen in the doc: https://triqs.github.io/dft_tools/unstable/tutorials/nio_csc.html

**Comment by quantumable** [comment] 2021-08-26 05:21
I modified the file plo.cfg converter.py nio.py I have an error during the calculation using nio.py
error:

Traceback (most recent call last):
  File "/home/TUTO_DMFT/nio.py", line 9, in <module>
    from triqs_dft_tools.block_structure import gf_struct_flatten
ImportError: cannot import name 'gf_struct_flatten' from 'triqs_dft_tools.block_structure' (/home/triqs/install/lib/python3.8/site-packages/triqs_dft_tools/block_structure.py)

but this seems to run with the script 
"dmft_ctqmc.py" that this site proposes (you can download the file "triqs3.tar" here [http://www.itp.uni-bremen.de/ag-wehling/teaching/dftdmft-tutorial/triqs2-to-triqs3/](url))

**Comment by quantumable** [comment] 2021-08-26 09:55
another question: I did the projection LOCPROJ = 1  : d : Pr ; LOCPROJ = 2 4 6 9  : p : Pr 
how to define the projections in the plo.cfg file?
i did this and got some errors.
 [Shell 2] # N p shell
LSHELL = 1
IONS = 2 4 6 9
CORR = False
TRANSFORM = 1.0  0.0  0.0
            0.0  1.0  0.0
            0.0  0.0  1.0

how to define the parameter IONS for the SHELL which comprises 4 atoms whose projections are made on 4 uncorrelated atoms

I tried IONS = [2 4 6 9] and IONS = [2, 4, 6, 9]

**Comment by the-hampel** [comment] 2021-08-26 10:31
Which version of DFTTools do you have installed? The error is related to the fact that the function `gf_struct_flatten` on.y exists in the unstable branch of triqs. If you want to use the older triqs installation just take the updated conveter.py and plo.cfg file of the tutorial with old nio.py script. That should work.

**Comment by the-hampel** [comment] 2021-08-26 10:36
What exactly is the error for the p-shell? Your IONS flag should work. As the documentation describes: 

> The sites can be given either by a list of integers IONS = 5 6 7 8 or by a range IONS = 5..8. The site indices must be compatible with the POSCAR file. Morever, sites can be marked to be identical by grouping them with brackets, i.e. IONS = [5 6] [7 8] will mark the sites 5 and 6 in the POSCAR (and of course also 7 and 8) to be idential. This will mark these correlated site as equivalent, and only one impurity problem per bracket group is generated.

If the sites are equivalent you can put them in brackets . Otherwise not. I would guess that your problem is related to the Transform section of your cfg file. You have to give one trafo matrix for each site. See https://triqs.github.io/dft_tools/unstable/guide/conv_vasp.html#transformation-file for details.

**Comment by the-hampel** [comment] 2021-08-27 09:15
Regarding this error: 
```
AssertionError: Negative eigenvalues of the overlap matrix:projectors are ill-defined
```
This is usually a sign, that the projectors are not well converged! Please check convergence of your KS eigenstates as I pointed out in the first place. Why do you want to keep the O-p states at all, if you are only interested in the Mn-d states? That would make maybe the creation of projectors simpler. This is definitely not a bug in the converter. It just tried to protect the user from doing something wrong.

**Comment by the-hampel** [comment] 2021-08-27 09:25
I am glad that the tutorial worked for you now. 

I cannot write for you the python scripts in detail to do so. I don't have time for that. From the tutorials of maxent: https://triqs.github.io/maxent/latest/documentation.html this should become more than clear. Did you try those? 

The analysis you ask about requires simply plotting the Matsubara Gf objects from triqs. Just load them from the h5 archive and plot them with the triqs plotting routines: https://triqs.github.io/triqs/unstable/documentation/manual/triqs/plotting_protocols/plotting/plotting.html . I believe there are many examples out there how to do this. You can load and plot a self energy simply like this: 
```
from h5 import HDFArchive
from triqs.gf import *
from triqs.plot.mpl_interface import plt,oplot

with HDFArchive('/path_to.h5','r') as h5:
    S_iw = h5['DMFT_results']['Sigma_freq_'+str(0)]
    
fig, (ax) = plt.subplots(1,1,figsize=(8,5))

ax.oplot(S_iw['up_0'][0,0].imag,'o',label='Im Sigma',markersize=2)
```

**Comment by quantumable** [comment] 2021-08-28 07:01
Thanks for your post I will write a script for it.

during the installation of vasp I have modified the locproj.F file as indicated in the tutorial by changing the line WRITE(99,'(4I6,"  # of spin, # of k-points, # of bands, # of proj" )') NS,NK,NB,NF    by    WRITE(99,'(4I6,F12.7,"  # of spin, # of k-points, # of bands, # of proj, Efermi" )') W%WDES%NCDIJ,NK,NB,NF,EFERMI et par la suite declarer EFERMI comme real (REAL(q) EFERMI). but during the calculation the value of the energy of fermi is not written here is the header of the LOCPROJ file  1   216    24     8   0.0000000  # of spin, # of k-points, # of bands, # of proj, Efermi 
for the single-shot calculation this is not a problem because I enter the value of the fermi energy by hand. but during self-consistent computation this poses a problem because it is a qutomatic computation. how to solve this problem so that the file LOCPROJ carries to its header the value of the energy of fermi.

ps: I used the version of vasp.5.4.4 and the version vasp.6.1.1 by modifying the file locproj.F and I have the same result.

**Comment by quantumable** [comment] 2021-08-29 07:18
I got the answer by following the method of compiling the unstable version instead.
[https://triqs.github.io/dft_tools/unstable/guide/conv_vasp.html](url)

**Comment by quantumable** [comment] 2021-08-29 11:18
how did you determine the value of the double counting. how did you choose the value 59 for the example of NiO i can use this value for my system?

**Comment by the-hampel** [comment] 2021-08-30 05:56
Sorry this has now really nothing to do anymore with dft_tools. I urge you to read on the theory of DFT+DMFT and the inherit problem of double counting of parts of the exchange-correlation accounted for in DFT. This is highly material specific. I believe here the value is chosen close to the FLL limit DC. Here is a good overview for NiO: https://doi.org/10.1016/j.elspec.2010.05.021 . A good overview for DFT+DMFT can be for example found here: https://www2.physnet.uni-hamburg.de/services/biblio/dissertation/dissfbPhysik/___Volltexte/Michael___Karolak/Michael___Karolak.pdf or in this book:  https://doi.org/10.1007/978-3-030-64904-3 . 

I will close the issue now. If you have a new specific problem please open a new one.

**Closed as completed by the-hampel** 2021-08-30 05:56 UTC

**Comment by quantumable** [comment] 2021-08-30 06:30
I have finished the Nio tutorial and I am now doing the calculation on system and I might have some questions about the code. So I wish we would not close the ticket yet.

**Comment by the-hampel** [comment] 2021-08-30 06:38
Github issues are not chat channels. This is only for discussions on a specific question, regarding problems with the code or feature requests. So if you have a new specific question, please open a new issue.
