### ISSUE TITLE
dmftproj: 'Bad value during floating point read' when reading a .dmftsym file

### ISSUE THREAD

**Issue by krivenko** [TRIQS/dft_tools#37] opened 2015-03-30 15:00 UTC
Hello everyone,

Today one of our students encountered an issue, which was reported before as TRIQS/triqs_0.x#148.
dmftproj does not want to read in symmetry information from a `.dmftsym` file.
```
 ocrijano@asterix01:~/TRIQS/CrCl3$ dmftproj
Welcome in DMFTPROJ: PROJECTION TO LOCALIZED BASIS


This prgm will build the Wannier projectors to the
localized orbitals of an atom onto which DMFT will be applied.


You are performing a computation
without Spin-Orbit.
using Paramagnetic Wien2k input files.
=======================================
Sorts of atoms =   2
Equivalent sites per each sort: 1 3


-------------------------------------
For the sort  1 :
The orbital l= 0 is included.
The orbital l= 1 is included.
The orbital l= 2 is included.

-------------------------------------
For the sort  2 :
The orbital l= 0 is included.
The orbital l= 1 is included.


The Eigenstates are projected in an energy window from   -0.40000 Ry  to     0.40000 Ry around the Fermi level.


=======================================
Basis representation for each sort.


-------------------------------------
For the sort  1 :
The atomic sort 1 is studied in the cubic basis representation.

The basis for s-orbital is still    1.000000
The basis for orbital l= 1 has the following properties :
 - number of ireps :  1
 - degree of each ireps :  3
The transformation matrix is block diagonal in the spin-space. The up/up and down/down blocks are the same and defined as :
    0.707107    0.000000    0.000000    0.707107    0.000000    0.000000
    0.000000    0.000000    0.000000    0.000000    1.000000    0.000000
   -0.707107    0.000000    0.000000    0.707107    0.000000    0.000000

The basis for orbital l= 2 has the following properties :
 - number of ireps :  2
 - degree of each ireps :  2  3
The transformation matrix is block diagonal in the spin-space. The up/up and down/down blocks are the same and defined as :
    0.000000    0.000000    0.707107    0.000000   -0.707107    0.000000    0.000000    0.000000    0.000000    0.000000
    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.707107    0.000000    0.707107    0.000000
    1.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   -0.707107    0.000000    0.707107    0.000000
    0.000000    0.000000    0.707107    0.000000    0.707107    0.000000    0.000000    0.000000    0.000000    0.000000



-------------------------------------
For the sort  2 :
The atomic sort 2 is studied in the cubic basis representation.

The basis for s-orbital is still    1.000000
The basis for orbital l= 1 has the following properties :
 - number of ireps :  1
 - degree of each ireps :  3
The transformation matrix is block diagonal in the spin-space. The up/up and down/down blocks are the same and defined as :
    0.707107    0.000000    0.000000    0.707107    0.000000    0.000000
    0.000000    0.000000    0.000000    0.000000    1.000000    0.000000
   -0.707107    0.000000    0.000000    0.707107    0.000000    0.000000




=======================================
Precisions about correlated orbitals.

-------------------------------------
For the sort  1 :
The irep  2 of orbital l=  2 is considered as correlated.
-------------------------------------
For the sort  2 :
No orbital is included as correlated.

=======================================
Symmetry operations of the system


Number of Symmetries =    1

Properties of the symmetry operations :
   alpha, beta, gamma are their Euler angles.
   iprop is the value of their determinant.

 SYM.OP.  alpha      beta     gamma     iprop
At line 95 of file /afs/physnet.uni-hamburg.de/users/th1_li/ikrivenk/TRIQS_build/dft_tools.git/fortran/dmftproj/setsym.f (unit = 8, file = 'CrCl3.dmftsym')
Fortran runtime error: Bad value during floating point read
```
`CrCl3.dmftsym`:
```
           1
           1           2           3           4           5           6
           7           8

Sym. op. :  1
   0.0   0.0   0.0  1       - euler angles: a,b,c; iprop 
   1.00000000000000       0.000000000000000E+000  0.000000000000000E+000
  0.000000000000000E+000   1.00000000000000       0.000000000000000E+000
  0.000000000000000E+000 -3.308722450212111E-024   1.00000000000000     
 Global->local coordinates rotation matrices
           1
   1.00000000000000       0.000000000000000E+000  0.000000000000000E+000
  0.000000000000000E+000   1.00000000000000       0.000000000000000E+000
  0.000000000000000E+000  0.000000000000000E+000   1.00000000000000     
   0.0   0.0   0.0  1       - euler angles: a,b,c; iprop 
           2
   1.00000000000000       0.000000000000000E+000  0.000000000000000E+000
  0.000000000000000E+000   1.00000000000000       0.000000000000000E+000
  0.000000000000000E+000  0.000000000000000E+000   1.00000000000000     
   0.0   0.0   0.0  1       - euler angles: a,b,c; iprop 
           3
   1.00000000000000       0.000000000000000E+000  0.000000000000000E+000
  0.000000000000000E+000   1.00000000000000       0.000000000000000E+000
  0.000000000000000E+000  0.000000000000000E+000   1.00000000000000     
   0.0   0.0   0.0  1       - euler angles: a,b,c; iprop 
           4
   1.00000000000000       0.000000000000000E+000  0.000000000000000E+000
  0.000000000000000E+000   1.00000000000000       0.000000000000000E+000
  0.000000000000000E+000  0.000000000000000E+000   1.00000000000000     
   0.0   0.0   0.0  1       - euler angles: a,b,c; iprop 
           5
   1.00000000000000       0.000000000000000E+000  0.000000000000000E+000
  0.000000000000000E+000   1.00000000000000       0.000000000000000E+000
  0.000000000000000E+000  0.000000000000000E+000   1.00000000000000     
   0.0   0.0   0.0  1       - euler angles: a,b,c; iprop 
           6
   1.00000000000000       0.000000000000000E+000  0.000000000000000E+000
  0.000000000000000E+000   1.00000000000000       0.000000000000000E+000
  0.000000000000000E+000  0.000000000000000E+000   1.00000000000000     
   0.0   0.0   0.0  1       - euler angles: a,b,c; iprop 
           7
   1.00000000000000       0.000000000000000E+000  0.000000000000000E+000
  0.000000000000000E+000   1.00000000000000       0.000000000000000E+000
  0.000000000000000E+000  0.000000000000000E+000   1.00000000000000     
   0.0   0.0   0.0  1       - euler angles: a,b,c; iprop 
           8
   1.00000000000000       0.000000000000000E+000  0.000000000000000E+000
  0.000000000000000E+000   1.00000000000000       0.000000000000000E+000
  0.000000000000000E+000  0.000000000000000E+000   1.00000000000000     
   0.0   0.0   0.0  1       - euler angles: a,b,c; iprop 
```
Could it be an installation/WIEN2k integration problem?
We are using WIEN2k 14.

**Comment by aichhorn** [comment] 2015-03-30 16:28
I checked with my installations, Wien2k 14.2 and TRIQS1.2, and it works. But I realized the following. In my case the dmftsym file looks like this:
          48
           1           2           3           4           5
           1           2           3           4           5
           1           2           3           5           4
           1           2           3           5           4
           1           2           3           5           4
           1           2           3           5           4
           1           2           3           4           5
           1           2           3           4           5
           1           2           4           3           5
           1           2           4           3           5
           1           2           4           5           3
           1           2           4           5           3
           1           2           4           5           3
           1           2           4           5           3
           1           2           4           3           5
           1           2           4           3           5
           1           2           5           3           4
           1           2           5           3           4
           1           2           5           4           3
           1           2           5           4           3
           1           2           5           4           3
           1           2           5           4           3
           1           2           5           3           4
           1           2           5           3           4
           1           2           5           3           4
           1           2           5           3           4
           1           2           5           4           3
           1           2           5           4           3
           1           2           5           4           3
           1           2           5           4           3
           1           2           5           3           4
           1           2           5           3           4
           1           2           4           3           5
           1           2           4           3           5
           1           2           4           5           3
           1           2           4           5           3
           1           2           4           5           3
           1           2           4           5           3
           1           2           4           3           5
           1           2           4           3           5
           1           2           3           4           5
           1           2           3           4           5
           1           2           3           5           4
           1           2           3           5           4
           1           2           3           5           4
           1           2           3           5           4
           1           2           3           4           5
           1           2           3           4           5

Sym. op. :  1
 360.0   0.0   0.0 -1       - euler angles: a,b,c; iprop 
   1.00000000000000       0.000000000000000E+000  0.000000000000000E+000
  1.232595164407831E-032   1.00000000000000       0.000000000000000E+000
  1.232595164407831E-032  1.232595164407831E-032   1.00000000000000     

Sym. op. :  2
 180.0   0.0   0.0  1       - euler angles: a,b,c; iprop 
  -1.00000000000000       0.000000000000000E+000  0.000000000000000E+000
 -1.232595164407831E-032  -1.00000000000000       0.000000000000000E+000
 -1.224646799147353E-016 -1.224646799147353E-016   1.00000000000000     


And so on. It is in principle the same, but you are missing some blank lines in your dmftsym. I know that this input/output issues are sometimes coming from using different compilers. What compiler did you use for the Wien2k installation? Can you try using gfortran to recompile lapw2?

**Comment by aichhorn** [comment] 2015-03-30 16:30
No, sorry. Your file looks correct. There are no blank lines in the global/local rotation matrices. 
But your system really has no symmetries? Only one symmetry operation?

**Comment by leopo** [comment] 2015-03-30 17:09
Hi Igor,

Can you post your indmftpr as well? I am puzzled by these lines in your outdmftpr

   Sorts of atoms =   2
   Equivalent sites per each sort: 1 3

which effectively says that you have 4 atoms per unit cell. Why then do you have 8 sites in your dmftsym?

**Comment by aichhorn** [comment] 2015-03-30 17:46
Or try to do a clean Wien2k iteration from a saved solution and run dmftproj again. It looks a bit like the dmftsym file is coming from a calculation that does not fit to the other output/input files...

**Comment by krivenko** [comment] 2015-04-03 13:17
@aichhorn 
> What compiler did you use for the Wien2k installation?

`ifort (IFORT) 12.1.4 20120410`

> Can you try using gfortran to recompile lapw2?

I can try if it is necessary...

> Or try to do a clean Wien2k iteration from a saved solution and run dmftproj again. It looks a bit like the dmftsym file is coming from a calculation that does not fit to the other output/input files...

OK, I will come to this issue and do what you suggest a bit later...

@leopo 
> Can you post your indmftpr as well? I am puzzled by these lines in your outdmftpr

```
2
1 3
3
cubic
1 1 2 0
0 0 2 0
01

cubic
1 1 0 0
0 0 0 0
-0.4 0.4
-0.225744727400
```

> Why then do you have 8 sites in your dmftsym?

As far as I understood, the calculation was done for a super-cell. Is this the problem?

**Comment by leopo** [comment] 2015-04-03 13:34
Yes, but if they were done for an 8-sites supercell, then your indmftpr should correspond to this supercell and have the same number of sites. 
One should, I think, compare struct and indmftpr to check that they have the same number of sites and multiplicities

**Comment by Kristanovski** [comment] 2015-04-05 18:37
I dont  think, that the problem is with different parameters in struct and indmftpr. i have the same error with Bornitrid. There are only 2 atoms in the cell, and 12 symmetry-operations...
ocrijano@asterix01:~/TRIQS/Bornitridwien/Bornitrid_test$ dmftproj
Welcome in DMFTPROJ: PROJECTION TO LOCALIZED BASIS


This prgm will build the Wannier projectors to the
localized orbitals of an atom onto which DMFT will be applied.


You are performing a computation
without Spin-Orbit.
using Paramagnetic Wien2k input files.
=======================================
Sorts of atoms =   2
Equivalent sites per each sort: 1 1


-------------------------------------
For the sort  1 :
The orbital l= 0 is included.
The orbital l= 1 is included.

-------------------------------------
For the sort  2 :
No orbital is included.


The Eigenstates are projected in an energy window from   -0.20000 Ry  to     0.20000 Ry around the Fermi level.


=======================================
Basis representation for each sort.


-------------------------------------
For the sort  1 :
The atomic sort 1 is studied in the cubic basis representation.

The basis for s-orbital is still    1.000000
The basis for orbital l= 1 has the following properties :
 - number of ireps :  1
 - degree of each ireps :  3
The transformation matrix is block diagonal in the spin-space. The up/up and down/down blocks are the same and defined as :
    0.707107    0.000000    0.000000    0.707107    0.000000    0.000000
    0.000000    0.000000    0.000000    0.000000    1.000000    0.000000
   -0.707107    0.000000    0.000000    0.707107    0.000000    0.000000




=======================================
Precisions about correlated orbitals.

-------------------------------------
For the sort  1 :
No orbital is included as correlated.

=======================================
Symmetry operations of the system


Number of Symmetries =   12

Properties of the symmetry operations :
   alpha, beta, gamma are their Euler angles.
   iprop is the value of their determinant.

 SYM.OP.  alpha      beta     gamma     iprop
    1       0.0       0.0       0.0       1
    2     240.0       0.0       0.0       1
    3     120.0       0.0       0.0       1
    4     180.0       0.0       0.0      -1
    5      60.0       0.0       0.0      -1
    6     300.0       0.0       0.0      -1
    7       0.0     180.0     120.0      -1
    8       0.0     180.0     240.0      -1
    9       0.0     180.0       0.0      -1
   10       0.0     180.0     300.0       1
   11       0.0     180.0      60.0       1
   12       0.0     180.0     180.0       1



-------------------------------------
Global-to-local-coordinates rotations


Properties of the symmetry operations :
   alpha, beta, gamma are their Euler angles.
   iprop is the value of their determinant.

  SORT    alpha      beta     gamma     iprop
    1       0.0       0.0       0.0       1
    2       0.0       0.0       0.0       1


=======================================

Reading of the file Bornitrid_test.almblm
At line 581 of file /afs/physnet.uni-hamburg.de/users/th1_li/ikrivenk/TRIQS_build/dft_tools.git/fortran/dmftproj/dmftproj.f (unit = 9, file = 'Bornitrid_test.almblm')
Fortran runtime error: Bad integer for item 1 in list input

its my indmftpr...
2
1 1
2
cubic
1 1 0
0 1 0
cubic
0 0 0
0 0 0
-0.2 0.2
-0.33982

**Comment by aichhorn** [comment] 2015-04-05 19:21
Kristanovski, your indmftpr file is not correct. Use this:

2
1 1
3
cubic
1 2 0 0 
0 0 0 0 
0
cubic
0 0 0 0 
0 0 0 0 
-0.2 0.2

In your version you defined no correlated orbitals, you specified the split of the shell in a way it should not be done. And you forgot the SO flag.
I am not sure if this solves the input error problem, since I never used dmftproj without acutally using it for calculating Wannier functions. Anyhow, you should use the modified script if you want Wannier functions.

**Comment by aichhorn** [comment] 2015-04-05 19:23
And the different parameters in struct and dmftproj will definitely lead to an error.

**Comment by Kristanovski** [comment] 2015-04-05 23:54
Ok, thanks for your tipps

**Comment by Kristanovski** [comment] 2015-04-06 00:38
This is the struct-file of CrCl3( 2D):
Wien97 struct file generated by XCrySDen program                               
P   LATTICE.NONEQUIV. ATOMS  8                                                 
MODE OF CALC=NREL                                                              
 11.121043 11.121043 32.748967 90.000001 90.000001119.999999                   
ATOM  -1: X=0.22199533 Y=0.11099016 Z=0.00000052
          MULT= 1          ISPLIT= 8
Cr         NPT=  781  R0=0.00005000 RMT= 2.30        Z: 24.0                   
LOCAL ROT MATRIX:    1.0000000 0.0000000 0.0000000
                     0.0000000 1.0000000 0.0000000
                     0.0000000 0.0000000 1.0000000
ATOM  -2: X=0.88864599 Y=0.44431695 Z=0.00000023
          MULT= 1          ISPLIT= 8
Cr         NPT=  781  R0=0.00005000 RMT= 2.30        Z: 24.0                   
LOCAL ROT MATRIX:    1.0000000 0.0000000 0.0000000
                     0.0000000 1.0000000 0.0000000
                     0.0000000 0.0000000 1.0000000
ATOM  -3: X=0.90660508 Y=0.12894678 Z=0.07691108
          MULT= 1          ISPLIT= 8
Cl         NPT=  781  R0=0.00010000 RMT= 2.08        Z: 17.0                   
LOCAL ROT MATRIX:    1.0000000 0.0000000 0.0000000
                     0.0000000 1.0000000 0.0000000
                     0.0000000 0.0000000 1.0000000
ATOM  -4: X=0.90660266 Y=0.77764610 Z=0.92308817
          MULT= 1          ISPLIT= 8
Cl         NPT=  781  R0=0.00010000 RMT= 2.08        Z: 17.0                   
LOCAL ROT MATRIX:    1.0000000 0.0000000 0.0000000
                     0.0000000 1.0000000 0.0000000
                     0.0000000 0.0000000 1.0000000
ATOM  -5: X=0.55529519 Y=0.42638172 Z=0.07690444
          MULT= 1          ISPLIT= 8
Cl         NPT=  781  R0=0.00010000 RMT= 2.08        Z: 17.0                   
LOCAL ROT MATRIX:    1.0000000 0.0000000 0.0000000
                     0.0000000 1.0000000 0.0000000
                     0.0000000 0.0000000 1.0000000
ATOM  -6: X=0.55529592 Y=0.12890008 Z=0.92309533
          MULT= 1          ISPLIT= 8
Cl         NPT=  781  R0=0.00010000 RMT= 2.08        Z: 17.0                   
LOCAL ROT MATRIX:    1.0000000 0.0000000 0.0000000
                     0.0000000 1.0000000 0.0000000
                     0.0000000 0.0000000 1.0000000
ATOM  -7: X=0.20401055 Y=0.77763707 Z=0.07691194
          MULT= 1          ISPLIT= 8
Cl         NPT=  781  R0=0.00010000 RMT= 2.08        Z: 17.0                   
LOCAL ROT MATRIX:    1.0000000 0.0000000 0.0000000
                     0.0000000 1.0000000 0.0000000
                     0.0000000 0.0000000 1.0000000
ATOM  -8: X=0.20400838 Y=0.42635797 Z=0.92308840
          MULT= 1          ISPLIT= 8
Cl         NPT=  781  R0=0.00010000 RMT= 2.08        Z: 17.0                   
LOCAL ROT MATRIX:    1.0000000 0.0000000 0.0000000
                     0.0000000 1.0000000 0.0000000
                     0.0000000 0.0000000 1.0000000
   1      NUMBER OF SYMMETRY OPERATIONS
 1 0 0 0.00000000
 0 1 0 0.00000000
 0 0 1 0.00000000
       1

And indmftpr for CrCl3:
2
2 6 
3
cubic 
1 1 2 0
0 0 2 0
01
0
cubic
1 1 0 0
0 0 0 0
-0.4 0.4
-0.225744727257

**Comment by Kristanovski** [comment] 2015-04-07 18:13
Can someone help me?  If i try to change the struct file :number of sites and multiplicities, then i have the problem with init_lapw....how can i compare number of sites and multiplicities in struct and indmftpr?

**Comment by aichhorn** [comment] 2015-04-08 05:50
Your struct file needs quite some work. From what I see it is built from XCrysDen, which is really not what you should do. Did you try to use w2web, for instance? The problem with your struct file is for instance that atoms 1 and 2 (the two Cr atoms) should be equvalent, but for numerical reasons Wien2k does not recognice that. One has Z=0.00000052 and the other one has Z=0.00000023, but both of them should be Z=0.00000000. Before you havn't fixed the struct file manually, or with some tool, you cannot really proceed with your calculation. It is not enough to change just the numbers for multiplicity and number of atoms.
Where did you get your crystal structure data from? Normally, that comes with symmetry information about equivalent atoms. You should have one set of coordinates for a Cr atoms, and one for a Cl atom. The other 6 positions in the unit cell are then determined by the symmetry properties. w2web is a very efficient tool for setting up the struct files properly.

**Comment by Kristanovski** [comment] 2015-04-08 18:00
thank you for your answer ,Markus. i created my struct file with w2web. now it works... :)

**Comment by aichhorn** [comment] 2015-04-09 09:22
Very good, I am closing this issue.

**Closed by aichhorn** 2015-04-09 09:22 UTC
