### ISSUE TITLE
Small bug in `SumkDFTTools.spaghettis(mesh=mesh)`

### ISSUE THREAD

**Issue by jrhui** [TRIQS/dft_tools#193] opened 2021-12-09 08:35 UTC
In `SumkDFTTools.spaghettis()`, `SK.lattice_gf()` is called. Inside `SK.lattice_gf()` `G_lattice` will be used if exists. However when the `mesh` passed into spaghettis() is inconsistence with `G_lattice.mesh`, the result will be wrong.

**Comment by the-hampel** [comment] 2021-12-09 13:24
Hi @zhl-95,

the problem is known and will be fixed with this PR: #177 . We can only merge it after we release the next version of triqs, because the PR will break backward compatibility. if you want to, you can try the PR with this git repo / fork: https://github.com/jkarp314/dft_tools/tree/sumk_mesh

Thanks for reporting this. I will keep the issue open until we merged the PR. 

Best regards,
Alex

**Comment by the-hampel** [comment] 2022-04-25 18:04
This should be fixed now with  #177 being merged into unstable.

**Closed as completed by the-hampel** 2022-04-25 18:04 UTC
Labels: bug
