### ISSUE TITLE
SumK set_Sigma raises FutureWarning

### ISSUE THREAD

**Issue by aichhorn** [TRIQS/dft_tools#131] opened 2020-02-19 14:23 UTC
This is just to not forget to fix it. With versions 2.2.x for TRIQS and DFTTools we get the FutureWarning when set_Sigma is called:

>>> SK.set_Sigma([ S.Sigma_iw, S.Sigma_iw_2 ])
/temp/AG-CMS/TRIQS/2.2/real/lib/python2.7/site-packages/pytriqs/gf/gf.py:359: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  dat = self._data[ self._rank * [slice(0,None)] + key_lst ]

**Comment by the-hampel** [comment] 2021-09-24 19:42
I think this problem is already fixed or not? At least I did not see the warning anymore in triqs/3.x.x?!

**Comment by the-hampel** [comment] 2023-02-10 15:46
TRIQS 2.2.x is no longer supported and the issue is fixed in ver > 3.0.x . Please reopen if issue appears again.

**Closed as completed by the-hampel** 2023-02-10 15:46 UTC
Labels: bug
