### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by pokornyv** [TRIQS/dft_tools#236] opened 2023-03-14 13:26 UTC
Dear all,
  I am trying to use DFTTools for some DFT+DMFT calculations and I run into an issue with `SK.spaghettis`. I use the docker://flatironinstitute/triqs image for DFTTools (version 3.1.0) and Wien2k-19.1 (compiled using ifort 2021.4.0, with the correction in lapw2 described in issue #127).

### Description

After running `lapw1 -band`, `lapw2 -almd -band` and `dmftproj -band` for the SrVO3 case from the tutorial and collecting the results into `SrVO3_band.h5` using the Wien2kConverter I run

```
SK = SumkDFTTools(hdf_file = SrVO3_band.h5, use_dft_blocks=True)

## set up dummy zero self-energy for the correlated shell for testing purposes
SE = []
for shell in range(SK.n_corr_shells):
  Sigma_w = BlockGf(mesh = MeshReFreq(window = (-4.0,4.0), n_w = 800), gf_struct = SK.gf_struct_solver_list[shell])
  Sigma_w.zero()
  SE.append(Sigma_w)
SK.set_Sigma(SE)

SK.spaghettis(broadening=0.03, plot_shift=0.0, plot_range=None, ishell=None, save_to_file='Akw_')
```

and I get the correct total spectral function A(k,w). But if I want to plot the t2g density only using 

```
SK.spaghettis(broadening=0.03,plot_shift=0.0,plot_range=None,ishell=0,save_to_file='Akw_')
```

I get an error

```
    SK.spaghettis(broadening=0.03, plot_shift=0.0, plot_range=None, ishell=0, save_to_file='Akw_')
  File "/usr/lib/python3.10/dist-packages/triqs_dft_tools/sumk_dft_tools.py", line 908, in spaghettis
    G_loc[bname] << self.rotloc(
  File "/usr/lib/python3.10/dist-packages/triqs_dft_tools/sumk_dft.py", line 445, in rotloc
    rot_mat_time_inv = self.rot_mat_all_time_inv
AttributeError: 'SumkDFTTools' object has no attribute 'rot_mat_all_time_inv'. Did you mean: 'rot_mat_time_inv'?
```

Is there a simple workaround this issue? Can I define the `rot_mat_all_time_inv` in some simple manner in my code?

### Steps to Reproduce

1. Run Wien2k-19.1 + dmftproj with -band for paramagnetic SrVO3 with the `case.indmftpr` file from tutorial.
2. Try to obtain the non-interacting spectral function A(k,w) for the t2g bands only.

### Versions

```
python3 -c "from triqs_dft_tools.version import *; show_version(); show_git_hash();"

You are using triqs_dft_tools version 3.1.0
You are using triqs_dft_tools git hash 6c94c72a8f0337b2eb0898d8f0a8a07d96121e74 based on triqs git hash a8924f99d1805de71e3d9b778f1b8aebba03f2d7
```

**Comment by the-hampel** [comment] 2023-03-23 21:39
Hi @pokornyv ,
I had a look at the specific part of the code. I am not an expert on the wien2k part, but I found a bug that could affect you. The functions `spaghettis` is supposed to read `rot_mat_all_time_inv` right before it calls the function `rotloc` that throws your error. The problem is that in 3.1.x no error is thrown when `rot_mat_all_time_inv` cannot be read from the hdf5 archive. This is a very special property for post-processing, so it is only used there. 

I wonder, if maybe in your h5 archive the data is not present? Can you check your h5 archive `SrVO3_band.h5` either in python or via h5ls if the group `dft_parproj_input` is present and in there you need a group called `rot_mat_all_time_inv`. 

In principle in line https://github.com/phibeck/dft_tools/blob/962b7798ed4cbcee8d9cae94903f01641bb65d05/python/triqs_dft_tools/sumk_dft_tools.py#L848 right before the rotloc call `rot_mat_all_time_inv` is loaded. The fact that you get the error that sumk.rot_mat_all_time_inv does not exist points to a problem loading it. 

I will push a fix to 3.1.x of triqs to throw a proper error when the object is not present in the h5. Right now it would just continue without telling the user. 

You might have to check manually unless you want to recompile the version. Let me know what an inspection of the h5 archive shows.

edit: fixed in d5cabfe54eb0d5d91c259578d08c53749efc79cb

Best,
Alex

**Comment by aichhorn** [comment] 2023-03-24 06:57
Hi Alex and @pokornyv,

I looked at your problem and I think I know where it comes from. The problem is that the documentation is not very precise at this point. If you want to project the spectral function to iorbitals, we are using what we call the theta projectors. These projectors, however, are not read in from convert_dft_input(). Instead, before using them, you have to convert also the partial projector inputs by calling convert_parproj_input(). Then, the arrays rot_mat_all etc. should be in the hdf5. Just try to add this one line after convert_dft_input to your code.

I dont know if we need to fix this in the code. One might throw and error that this property is not converted form dft to hdf5. But we can describe this also more precisly in the documentation.

Best,
Markus

**Comment by aichhorn** [comment] 2023-03-24 06:59
Thanks for the fix Alex! I guess this makes the error message more clear. However, I will have a look at the docs to make this more clear what is needed to be done. Obviously, nobody used this feature until now except myself...

**Comment by AlynJ** [comment] 2023-03-28 09:56
Hi @aichhorn and @the-hampel (and @pokornyv),

I have been rewriting the spectral function routines in sumk_dft_tools.py to condense them down to a single routine for a particular post-processing quantity (say the density of states) which knows how to deal with the specific DFT code inputs (using the self.dft_code variable). I've updated the documentation for it in my repo too. As it's always the case, other things have got in the way so I haven't looked at it much recently. It's pretty much there I think (need to do a few more tests and merge it with the recent pull requests) - I'd be happy to discuss this before making a pull request.

Best,
Alyn

**Comment by pokornyv** [comment] 2023-04-05 16:54
Hi.
  Apart from calling `convert_parproj_input()` to store the matrices in hdf5 I also had to register them to SumkDFTTools,

```
with HDFArchive('SrVO3_band.h5') as ar:
	SK.rot_mat_all = ar['dft_parproj_input']['rot_mat_all']
	SK.rot_mat_all_time_inv = ar['dft_parproj_input']['rot_mat_all_time_inv']
```

but it works now.

Thank you all for the help.

**Comment by the-hampel** [comment] 2023-04-05 18:21
Very good. I am not sure why you had to update the sumk object manually. This should be done upon calling spaghettis no? But I am happy to hear that this worked now for you.

@AlynJ I am happy to discuss at some point the following weeks. We can arrange a Zoom call via eMail if you like. Feel also free to open a PR if I should have a look before. 

I will close this issue now. 

- Alex

**Closed as completed by the-hampel** 2023-04-05 18:21 UTC
Labels: bug
