### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Reyhanehe** [TRIQS/dft_tools#110] opened 2018-12-29 21:27 UTC
Dear Triqs Group
Hi
I want to run dft+dmft calculation considering SO. But when I run  "case.py" for the SrVO3 compound, I have error that:
"File "case.py", line 64, in <module>
 S.solve(h_int=h_int, **p)
File "............./cthyb_solver.py", line 95, in solve
solve_status = SolverCore.solve(self, **params_kw)
.. Error .. calling C++ overload 
.. solve() -> void 
.. in implementation of method SolverCore.solve
.. C++ error was : 
.. Triqs runtime error at .........../fundamental_operator_set.hpp : 147

Operator with indices (down,0) does not belong to this fundamental set!
.. Error occurred on node 0"
can you help me to fix this error?
Thanks a lot
Reyhaneh

**Comment by mzingl** [comment] 2018-12-29 22:42
This issue is a duplicate of TRIQS/triqs#664, TRIQS/cthyb#101

Please refrain from duplicating issues and opening the same issue on triqs, cthyb and dfttools. These issues will NOT be answered.  Further, please assign an adequate name - 'error' is not a reasonable one for an issue.
Issues need to be reproducible and clearly stated for us in order to analyse a possible problem. 
It is impossible for us to help you, as we do not know what the content of your file 'case.py' is, where it is coming from and what you are trying to do.

**Comment by mzingl** [comment] 2018-12-29 22:58
Also, before posting your whole 'case.py' file, please try to provide a minimal working example where the error still exists. 
A guess: Judging from your error message it is likely that your Hamiltonian has not the correct operator structure. It can only have the same indices as those of e.g. S.G_iw.

**Comment by Reyhanehe** [comment] 2018-12-29 23:17
Dear Mr. Mizgl
Thank you to you for your comment.
so I close the othe same question and ask my question in here
I want to run DFT+DMFT+so calculation for compounds. I used the "case.py " same "case.py" that is in triqs site but I chaged some part of it to considering SO and also for FLL DFT+DMFT calculation.
I write them for you:
"dc_type = 1                     
.
.
# Construct U matrix for density-density calculations:
h_int = h_int_density(spin_names, orb_names, Umat, Upmat, get_mkind)
.
.
    # Init the DC term and the real part of Sigma, if no previous runs found:
      .
      . 
         S.Sigma_iw << SK.dc_imp[0]['ud'][0,0]
.
.
.
    # Solve the impurity problem:
    S.solve(h_int=h_int, **p)
. 
.
.
.
    SK.set_Sigma([ S.Sigma_iw ])
chemical_potential = SK.calc_mu( precision = 0.000001 )
.
.
.
if (mpi.is_master_node()):
  f=open(dft_filename+'.qdmftup','a')
  f.write("%.16f\n"%(correnerg*0.5))
  f.close()
  f=open(dft_filename+'.qdmftdn','a')
  f.write("%.16f\n"%(correnerg*0.5))
  f.close()
"
can you please help me to fix my problem?
Thank you very much
Reyhaneh

**Comment by mzingl** [comment] 2018-12-30 00:10
Dear Reyhaneh,

As far as I recall there is no file named 'case.py' in the dft_tools repository present.
I can only guess that you refer to the following user guide [SrVO3](https://triqs.github.io/dft_tools/master/guide/SrVO3.html), but you try to run it now with SOC.

At this point, I can guess what goes wrong:
Judging from your error message it is likely that your Hamiltonian has not the correct operator structure. It can only have the same indices as those  of e.g. S.G_iw. Try to print SK.gf_struct_solver[0] first.
You might then see that the indices are not the same as those you use with spin_names and orb_names.
You can also print h_int. Again, you might see that this Hamiltonian has the wrong indices. Hence, you will have to construct it correctly for the new indices structure.

Although, we have pointed this out in multiple of your issues (#104 #103 #93),
I'd like to strongly emphasize it here again:
DFT+DMFT+SOC - although in principle possible with DFTTools - is currently NOT
documented in our user guides and is by no means trivial to do.
We currently do NOT provide any teaching (e.g. as user guide) or support for SOC calculations.
Such calculations require an in-depth understanding of the triqs, cthyb and dft_tools code.

Best,
Manuel

**Comment by Reyhanehe** [comment] 2018-12-30 15:19
Dear Mizgl
Thank to you for your response.
"As far as I recall there is no file named 'case.py' in the dft_tools repository present.
 I can only guess that you refer to the following user guide SrVO3, but you try to run it now with SOC.":This means that "dft_dmft_cthyb.py" is not the case.py that I need for DFT+DMFT calculation?
If yes can you please help me to find the correct case.py for this calculation?note that I add one part at the end of this file to doing full charge self consistency DFT+DMFT
(I wrote them in my before comment in this question).
another point is that I know the theory of DFT+DMFT in detail, but adding SO is not possible when I doing things that are in dmftprojtutorial and triqs site.I need to run this calculation for my compound as soon as possible. can you please help me to run this calculation now?
Or can you please send the tutorial of it to my E-mail address?
my Email address is: "r.ebrahimijaberi@sci.ui.ac.ir"
thank you very much
Reyhaneh

**Closed** 2018-12-30 22:31 UTC
