### ISSUE TITLE
Postprocessing with wannier90 input

### ISSUE THREAD

**Issue by ZhijieFan** [TRIQS/dft_tools#137] opened 2020-04-20 21:14 UTC
Is it possible to do postprocessing using wannier90 input data?

We are currently trying to do DFT+DMFT calculation using QE+Wannier90+Triqs.

We would like to calculate the transportation properties and k-resolved spectral function. However it seems that the documents are written for Wien2k inputs.

**Comment by mzingl** [comment] 2020-04-20 23:00
Dear ZhijieFan,

currently some post-processing functionalities are only available with Wien2k and VASP. (For VASP only a little piece of reading velocities for the transport hasn't been implemented, but this is on our list.)

1.) k-resolved spectral function
We have a few functionalities in the TRIQS lattice tools and in TRIQS/tprf which I use to obtain A(k,w). We are working on making DFTTools compatible with lattice tools, which will add this functionality too. Until then I can provide some help on how to use lattice tools to obtain A(k,w).

2.) Transport
This is a bit more tricky. We calculate transport in the band basis using velocities obtained in Wien2k as elements of the momentum operator. This cannot be done with only the Wannier Hamiltonian at hand. However, one could neglect possible inter-band transitions in multi-band cases and calculate only band-diagonal velocities, which are then simply derivatives of eps_k. That is something we should definitely implement, but haven't done so far.

Best, Manuel

**Comment by ZhijieFan** [comment] 2020-04-21 00:14
Dear Manuel,

Thank you for your reply. It is very kind of you to provide help on calculating A(k,w). You said that we can use TRIQS lattice tool to obtain A(k,w), how can we do so? 

By the way, I do have a question regarding the **projectors** which is related to the calculation of A(k,w). 

Why are the projectors for Wannier90 input are all set to be identity matrices and k-independent?

I think that to calculate A(k,w), we have to upfold the local orbital self-energies to band basis to obtain lattice green function whose imaginary part is basically A(k,w). In this process, the k-dependence of self-energy only comes from the projectors. However, after reading the source code, I figured that the projectors are k-independent, which is really confusing. 

Thank you!

Best,
Zhijie

**Comment by mzingl** [comment] 2020-04-22 14:49
Dear Zhijie,

this script [calculate_Akw.txt](https://github.com/TRIQS/dft_tools/files/4516789/calculate_Akw.txt) shows how to construct a tight binding object. It also loads and interpolates a self-energy, and then calculates A(k,w). Note that you need to have TRIQS/tprf installed for this to work. (It's in a txt file, because github doesn't allow to upload py files.) You will need to adapt it to your own needs.

To your question on the projectors: You are in principle right. However, if you have already a Wannier Hamiltonian, then you can also directly perform DMFT in the orbital basis, i.e. the lattice k-sum is also performed in the orbital basis. Therefore the projectors select only which orbitals are correlated (with ones on the respective diagonal elements).

The problem is that this is inconsistent and confusing for the user, because the meaning of the 'hopping' variable is different whether one uses Wien2k/Vasp or Wannier90. We are currently discussing how we can make this clearer and simpler.

I'll let this issue open as a reminder for us.

Best, Manuel

**Comment by ZhijieFan** [comment] 2020-04-24 20:56
Thank you for the script. I will read it and see what I can learn from it.

My original guess for the projector problem is that for Wannier hamiltonian, we are already in the orbital basis. In this case, there is no need for extra projections, so the projector is only to pick the correlated orbitals. The k dependence is only related to H(k) in the non-interacting Green's function G0 which can be calculated for arbitrary k points using the Wannier90 ouput H(R). Thank you for clearifying it.

**Comment by phibeck** [comment] 2022-04-22 21:06
Dear Zhijie,

just to follow up on your original question. The k-resolved spectral function is now implemented, you can check out an example here: https://flatironinstitute.github.io/solid_dmft/tutorials/correlated_bandstructure/plot_correlated_bands.html
Note that this works for the band basis of the downfolded Hamiltonian only, not the original Kohn-Sham states. So if there is disentanglement during the Wannierization, these contributions will not be included.

Regarding the transport properties, this is also implemented and will be merged into dft_tools/unstable within the next 2-3 weeks with an example. If you want to try it out beforehand, you can check out the development branch https://github.com/phibeck/dft_tools/tree/optics

Let me know if you have further questions.

Best,
Sophie

**Comment by the-hampel** [comment] 2023-02-10 15:45
Will be fixed with https://github.com/TRIQS/dft_tools/pull/230

**Closed as completed by the-hampel** 2023-02-10 15:45 UTC
Labels: enhancement
